# Generated by Django 3.2.18 on 2023-06-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de consulta')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_evento', models.DateField(verbose_name='Fecha de evento')),
                ('imagen_evento', models.ImageField(upload_to='imagenes/', verbose_name='Foto del evento')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100)),
                ('baja', models.BooleanField(default=0)),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
            ],
            options={
                'verbose_name_plural': 'Guias',
            },
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100)),
                ('baja', models.BooleanField(default=0)),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('atractivos', models.IntegerField(choices=[(1, 'Naturales'), (2, 'Culturales'), (3, 'Religiosos'), (4, 'Deportivos'), (5, 'Todos')], default=1)),
                ('aceptar', models.BooleanField(default=0)),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.consulta')),
            ],
            options={
                'verbose_name_plural': 'Turistas',
            },
        ),
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=100, verbose_name='Atractivo')),
                ('ubicacion', models.TextField(verbose_name='Ubicación')),
                ('imagen_atractivo', models.ImageField(upload_to='imagenes/', verbose_name='Foto del atractivo')),
                ('guia', models.ManyToManyField(to='administracion.Guia')),
            ],
            options={
                'verbose_name_plural': 'Atractivos',
            },
        ),
    ]
